FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY data_preprocessing /app/data_preprocessing


EXPOSE 8000

CMD ["python", "data_preprocessing/cleaning.py"]
