FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY model_serving /app/model_serving

CMD ["sh", "/app/model_serving/start_model_serving.sh"]
