global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['data_ingestion:5000']

  - job_name: 'data_preprocessing'
    static_configs:
      - targets: ['data_preprocessing:8000']

  - job_name: 'model_training'
    scrape_interval: 5s
    static_configs:
      - targets: ['model_training:8001']

  - job_name: 'model_serving'
    static_configs:
      - targets: ['model_serving:5002']

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['localhost:9182']
