{
 "title": "Fraud Detection",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "File Uploads Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "file_uploads_total", "query": "file_uploads_total", "legendFormat": "Total Uploads" }
   ]
  },
  {
   "title": "File Upload Bytes Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "file_upload_bytes_total", "query": "file_upload_bytes_total", "legendFormat": "Total Bytes" }
   ]
  },
  {
   "title": "File Upload Errors Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "file_upload_errors_total", "query": "file_upload_errors_total", "legendFormat": "Upload Errors" }
   ]
  }
 ]
}